import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { NextAuthProvider } from "../Providers";

export const metadata = {
  title: "DUEL NEXUS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className="bg-gray-900 antialiased">
          <Header />

          <div className=" min-h-screen mt-20 mx-auto px-4 sm:px-6 lg:px-8">
            {children}
          </div>

          <Footer />
        </body>
      </html>
    </NextAuthProvider>
  );
}
